version: "3.2"
services:
  mssql:
    image: microsoft/mssql-server-linux:2017-GA
    container_name: mssql-server
    ports:
      - "1433:1433"
    volumes:
      - ./mssql:/var/opt/mssql/
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: P@ssw0rd!
